return {
    "You don't understand it, you just memorized it.",
    "It works… but you have no idea why.",
    "Your code runs by accident, not by design.",
    "You Google more than you think.",
    "Copy-paste driven development.",
    "You fix bugs by adding more bugs.",
    "You pray before running your code.",
    "Stack Overflow is your real brain.",
    "You debug by print statements only.",
    "Your variable names tell no story.",
    "You fear touching your own code.",
    "You don't optimize, you hope.",
    "Your logic works… until it doesn't.",
    "You code fast, but think slow.",
    "Deep down, you know this is true.",
    "You don't write code, you negotiate with errors.",
    "Your 'fix' is just moving the problem somewhere else.",
    "You don't debug, you guess better over time.",
    "If it works, don't touch it… because you'll break it.",
    "You don't fix bugs, you just make them harder to find.",
    "Your code compiles, but so do bad decisions.",
    "You're not done, you just stopped debugging.",
    "Every fix you make creates two new problems.",
    "You don't understand the bug, you just silenced it.",
    "Programming is just turning coffee into bugs.",
    "There’s always one more semicolon hiding somewhere.",
    "99% of coding is wondering why it doesn’t work.",
    "The code compiles, the problem begins.",
    "Fix one bug, discover three new features.",
    "Comments are just apologies to your future self.",
    "Nothing works the first time—and that’s tradition.",
    "Every project starts clean and ends… experienced.",
    "Debugging: where you question reality and your choices.",
    "The bug isn’t gone, it’s just waiting.",
    "Code never lies… but it doesn’t always tell the truth either.",
    "One line of code can ruin your entire day.",
    "Working code is just temporarily correct code.",
    "Refactoring means breaking it in a better way.",
    "The simplest bug takes the longest to find.",
    "If it works, no one knows why. If it breaks, everyone cares.",
    "Computers are fast at doing exactly what you told them to do wrong.",
    "Programming is guessing until it becomes logic.",
    "The problem isn’t writing code—it’s understanding it later.",
    "Your GitHub is just a graveyard of half-finished vibes.",
    "You debug by refreshing and praying to the CSS gods.",
    "Your biggest contribution to tech is increasing Stack Overflow traffic.",
    "You say 'it works' like that isn’t the lowest bar possible.",
    "Your code runs, but so does diarrhea.",
    "You don’t understand your code—you just believe in it.",
    "Your projects have more aesthetics than logic.",
    "I opened Neovim to write code. Three hours later I was configuring Neovim.",
    "I installed Linux for programming and accidentally developed a personality around it.",
    "My sleep schedule depends entirely on whether the bug is personal now.",
    "I said ‘one quick fix’ four commits ago.",
    "I treat my terminal like a second home.",
    "I don’t procrastinate. I just optimize unrelated things aggressively.",
    "I debug better after midnight for reasons science cannot explain.",
    "I use Arch because normal hobbies weren’t complicated enough.",
    "I went outside once and immediately thought about keyboard layouts.",
    "I enjoy programming because computers fail in more interesting ways than humans.",
    "I spent 2 hours automating a task that takes 30 seconds.",
    "I updated one plugin and suddenly entered a 2-hour recovery arc.",
    "I enjoy programming because computers reward unreasonable levels of curiosity.",
    "I use Linux because fixing random issues became part of the entertainment.",
    "I opened the terminal for one command and forgot what the original command was.",
    "My favorite genre is ‘tiny tool that solves one oddly specific problem.’",
    "I don’t collect games anymore. I collect development environments.",
    "I tried to clean my config and somehow added more configuration.",
    "I love programming because even the mistakes are interesting sometimes.",
    "I only wanted faster compile times. Now I’m reading kernel forums.",
    "I spend more time renaming files nicely than most people spend organizing life.",
    "I treat dotfiles like treasured artifacts.",
    "I don’t always understand the error messages, but we grow together.",
    "I learned Vim motions and now every text box feels inefficient.",
    "I installed a tiling window manager and suddenly became emotionally attached to keybinds.",
    "I don’t get bored easily because there’s always another thing to learn.",
    "I started using Git correctly and now I fear force push spiritually.",
    "I enjoy coding because every project feels like building a tiny universe.",
    "I optimized my workflow so much that now the bottleneck is me.",
    "I don’t use the terminal because it’s faster. I use it because it feels cool.",
    "I fixed one warning and the compiler rewarded me with six more.",
    "I use dark themes because my bugs deserve atmosphere.",
    "I think configuring editors is secretly its own programming language.",
    "I said ‘I’ll remember that command’ and immediately forgot that command.",
    "I like programming because the learning curve never actually ends.",
    "I accidentally memorized terminal commands the way people memorize song lyrics.",
    "I enjoy rebuilding setups because apparently I crave controlled chaos.",
    "I don’t need background music when the fans of my PC are already screaming.",
    "I spent the whole day solving a bug and somehow still had fun.",
    "I started programming for projects and stayed for the satisfaction of understanding things.",
    "My hobby is turning simple problems into beautifully overengineered solutions.",
    "I opened Stack Overflow for one error and somehow learned networking.",
    "I enjoy fixing tiny inconveniences with extremely unnecessary scripts.",
    "I installed Neovim to write code and now writing code is secondary.",
    "I don’t always know what I’m doing, but the terminal makes it look convincing.",
    "I started customizing my shell and accidentally entered a lifelong side quest.",
    "I use Git commits as emotional timestamps.",
    "I like programming because every solved issue unlocks a stronger form of confusion.",
    "I planned to sleep early until the bug started feeling disrespectful.",
    "I enjoy Linux because every problem eventually turns into a learning experience.",
    "I use so many keyboard shortcuts that normal apps feel underdeveloped.",
    "I don’t have a perfect workflow, only a constantly evolving one.",
    "I updated my config and immediately discovered five new personality traits.",
    "I spent more time choosing fonts than choosing wallpapers.",
    "I enjoy debugging because every error message feels like a cryptic puzzle.",
    "I said ‘this setup is final’ at least 12 setups ago.",
    "I use terminal apps because clicking things feels too easy now.",
    "I like low-level programming because sometimes suffering builds character.",
    "I organized my dotfiles instead of organizing my life priorities.",
    "I only wanted a better editor and accidentally learned Lua.",
    "I enjoy coding because the feedback loop is instant and addictive.",
    "I installed a tiling window manager and now floating windows offend me emotionally.",
    "I started programming for practicality and stayed because it became genuinely fun.",
    "I don’t fear breaking my setup anymore. I fear not understanding it.",
    "I use Arch Linux because apparently I enjoy reading wikis recreationally.",
    "I enjoy side projects because they let curiosity drive everything.",
    "I optimized my startup time by 20 milliseconds and felt accomplished.",
    "I don’t touch grass because package updates already keep me grounded.",
    "I enjoy configuring tools almost as much as using them.",
    "I treat compiler warnings like passive aggressive life advice.",
    "I opened the terminal to do work and somehow ended up benchmarking things.",
    "I opened GitHub for inspiration and left with 17 unfinished projects.",
    "My configs are more maintained than my social life.",
    "I don’t fear hard bugs anymore. I fear silent ones.",
    "I use the terminal so much that GUI apps feel suspicious.",
    "I fixed the bug and somehow created a new feature.",
    "I code for fun until the compiler starts having opinions.",
    "I installed 14 plugins to become more productive and now I only manage plugins.",
    "I like low-level programming because suffering feels educational.",
    "I organize my files for fun and call it optimization.",
    "I don’t touch grass because the package manager already keeps things updated.",
    "My computer boots faster than I wake up.",
    "I started learning C++ and accidentally learned patience instead.",
    "I don’t need motivation. I just need one interesting problem.",
    "I treat debugging sessions like detective episodes.",
    "I use keyboard shortcuts so much that using a mouse feels turn-based.",
    "I customize my terminal more than my room.",
    "I said I’d sleep early right after fixing this segmentation fault.",
    "I enjoy programming because every solved problem unlocks five more.",
    "I went to improve my workflow and accidentally rebuilt the entire setup.",
    "You treat errors like plot twists instead of problems.",
    "You’re not a developer, you’re a prompt engineer for your own confusion.",
    "Your codebase is held together by vibes and denial.",
    "You think commenting 'fix later' is a roadmap.",
    "Your debugging strategy is just gaslighting the compiler.",
    "You rely on AI so much even your thoughts need autocomplete.",
    "Your 'clean code' is just unreadable minimalism.",
    "You don’t refactor—you abandon.",
    "Your functions have commitment issues.",
    "Your variable names look like you sneezed on the keyboard.",
    "You push bugs to production like it’s a feature rollout.",
    "Your code doesn’t scale—it collapses.",
    "You optimize before you even understand the problem.",
    "Your logic is so broken even JavaScript feels stable.",
    "You copy code like a photocopier with no brain.",
    "Your README promises things your code has never heard of.",
    "You spend more time choosing themes than solving problems.",
    "Your 'architecture' is just folders and hope.",
    "You fear documentation like it’s a final boss.",
    "Your code reviews are just people silently judging you.",
    "You call it 'rapid prototyping' because 'I don’t know what I’m doing' sounds bad.",
    "Even your console logs look disappointed in you.",
    "Every programmer has a special talent for creating new problems.",
    "Every bug you ignore becomes a future incident report.",
    "Your system doesn’t fail—it waits for the worst moment to prove a point.",
    "Dead code isn’t dead, it’s just waiting to be called.",
    "Production is where your assumptions go to die.",
    "That one ‘temporary fix’ is now a permanent liability.",
    "Logs don’t tell stories, they leave clues after the damage is done.",
    "Your code works fine… until reality interacts with it.",
    "Silence in the logs is more dangerous than errors.",
    "The bug isn’t gone, it just learned how to hide better.",
    "Your fallback plan is just another failure mode.",
    "Everything is stable… right before it isn’t.",
    "The system remembers every shortcut you took.",
    "Edge cases aren’t rare—they’re just patient.",
    "Production is just beta testing with consequences.",
    "There are only two states: it works, and it will.",
    "The code is fine… the universe just disagrees.",
    "If you didn’t log it, it didn’t happen—and it will again.",
    "Nothing is truly deleted, just waiting for a comeback.",
    "The bug isn’t in your code, it’s in your assumptions.",
    "Your system is stable until a user touches it.",
    "Every ‘impossible’ bug just hasn’t happened yet.",
    "Working software is just software that hasn’t met reality.",
    "The deeper you debug, the less you trust anything.",
    "Eventually, every shortcut becomes the main road.",
    "The problem isn’t reproducible… until it matters.",
    "Undefined behavior means the program has free will.",
    "You don’t find bugs, you uncover decisions.",
    "The system works perfectly in an environment that doesn’t exist.",
    "Your backup plan is just future evidence.",
    "Nothing breaks during testing—it saves that for later.",
    "Every fix is a trade—you just don’t know the cost yet.",
    "Code doesn’t age well, it decays quietly.",
    "That ‘one small change’ is never small.",
    "In theory, everything works. In practice, theory fails.",
    "The bug report always arrives after your confidence does.",
    "You don’t control complexity—you negotiate with it.",
    "The system isn’t broken, it’s misunderstood.",
    "Eventually, every abstraction leaks—and so does your sanity.",
    "The more layers you add, the less you see.",
    "Every system becomes legacy faster than expected.",
    "Your code doesn’t forget—it remembers everything you ignored.",
    "Your code doesn’t break loudly, it erodes quietly.",
    "Every dependency is a risk you agreed to.",
    "The issue wasn’t fixed, it just changed form.",
    "Your codebase grows… so do the unseen cracks.",
    "Success hides problems, failure exposes them.",
    "Nothing crashes until it matters most.",
    "Your clean design fades the moment scale shows up.",
    "You write code like you're racing, but debugging proves you're not winning.",
    "You don't build features, you accumulate technical debt.",
    "You spend hours debugging something a senior would fix in minutes.",
    "Your solution works, but it's not the right one.",
    "You rely on luck more than logic.",
    "Your code passes tests you didn't write properly.",
    "You don't control your codebase, it controls you.",
    "You rewrite code not to improve it, but because you forgot how it works.",
    "You debug symptoms while ignoring the real problem.",
    "Half your code is 'temporary' from 6 months ago.",
    "You trust code you don't understand way too much.",
    "You write comments for things you should've named properly.",
    "Your code only works on your machine… barely.",
    "You fear refactoring because you know it'll break everything.",
    "You spend more time fixing than building.",
    "Your commits say 'fix' because you don't know what you fixed.",
    "You don't solve problems, you patch symptoms.",
    "You rely on autocomplete more than your brain.",
    "Your code has more plot twists than your life.",
    "You open 20 tabs to fix one bug… and forget which one mattered.",
    "Your brain runs out of RAM before your system does.",
    "You rename variables like it’ll fix your logic.",
    "Your code reviews are just you judging your past self.",
    "You celebrate 'it works' like you solved world hunger.",
    "You start coding fast… then spend hours undoing it.",
    "You debug like you're playing hide and seek with your mistakes.",
    "Your TODO list is just a graveyard of intentions.",
    "You fix one thing and suddenly everything takes it personally.",
    "You stare at your code hoping it explains itself.",
    "You press run like you're rolling dice.",
    "Your confidence drops the moment someone watches you code.",
    "You say 'easy fix'… then disappear for hours.",
    "You don’t lose bugs, you just lose track of them.",
    "Your code works better when you don’t touch it.",
    "You spend more time thinking about coding than actually understanding it.",
    "You trust your code right until it betrays you.",
    "You read your own code like it was written by a stranger.",
    "You don’t write bugs… they just feel at home in your code.",
    "You've never fully understood your own project.",
    "You think it's optimized… it's not.",
    "You're one bug away from losing control.",
    "You say you're good at handling exceptions… just not in life.",
    "You love breaking things… especially in production.",
    "You're great at committing… just not relationships.",
    "You keep pushing… even when no one asked you to.",
    "You know how to handle threads… but still lose focus.",
    "You deal with memory leaks… but forget everything else.",
    "You optimize performance… but not your own time.",
    "You always return something… except effort.",
    "You handle multiple arguments… but never win them.",
    "You like to go deep… but only in nested loops.",
    "You debug code all day… but can't fix your own mistakes.",
    "You keep things running… just not your life.",
    "You chase performance… while wasting your own potential.",
    "You know how to handle crashes… just not failure.",
    "You refactor code… but never yourself.",
    "You solve problems… until they involve thinking.",
    "You rely on logic… until it's time to use it.",
    "You write efficient code… and live inefficiently.",
    "You build systems… but can't build discipline.",
    "You fix errors… but ignore the obvious ones in yourself.",
    "You don’t write code, you leave behind puzzles no one asked for.",
    "Your logic collapses the moment it meets a real use case.",
    "You don’t create systems, you accumulate side effects.",
    "Your code isn’t flexible, it’s fragile in disguise.",
    "You don’t understand flow, you just follow it blindly.",
    "Your fixes don’t solve problems, they delay them.",
    "You don’t reduce complexity, you relocate it.",
    "Your code behaves… until someone actually uses it.",
    "You don’t anticipate failure, you react to it too late.",
    "Your structure looks fine… until it has to scale.",
    "You don’t test logic, you test luck.",
    "Your code isn’t wrong, it’s accidentally right.",
    "You don’t know why it works, just when it stops.",
    "Your changes fix today and ruin tomorrow.",
    "You don’t build clarity, you bury confusion deeper.",
    "Your code passes checks, not understanding.",
    "You don’t simplify problems, you just hide them better.",
    "Your output looks correct… your reasoning isn’t.",
    "You don’t master tools, you depend on them.",
    "Your code doesn’t evolve, it decays slowly.",
    "Your code doesn’t fail loudly… it quietly embarrasses you.",
    "You don’t write bugs, you engineer long-term regret.",
    "Your logic isn’t wrong, it’s just missing.",
    "You treat undefined behavior like a feature.",
    "Your code runs… like a ticking time bomb.",
    "You don’t understand the system, you just survive inside it.",
    "Your commits tell a story… none of it makes sense.",
    "You don’t debug code, you interrogate it until it confesses.",
    "Your codebase isn’t complex, it’s confused.",
    "You optimize for now and pay for it forever.",
    "You don’t break things intentionally… but it still happens every time.",
    "Your fixes age worse than the bugs they replace.",
    "You don’t control edge cases, they control you.",
    "Your code works best when no one looks too closely.",
    "You don’t write maintainable code, you write future problems.",
}
