return {
    "You don't understand it, you just memorized it.",
    "It works… but you have no idea why.",
    "Your code runs by accident, not by design.",
    "You Google more than you think.",
    "Copy-paste driven development.",
    "You fix bugs by adding more bugs.",
    "You pray before running your code.",
    "Stack Overflow is your real brain.",
    "You debug by print statements only.",
    "Your variable names tell no story.",
    "You fear touching your own code.",
    "You don't optimize, you hope.",
    "Your logic works… until it doesn't.",
    "You code fast, but think slow.",
    "Deep down, you know this is true.",
    "You don't write code, you negotiate with errors.",
    "Your 'fix' is just moving the problem somewhere else.",
    "You don't debug, you guess better over time.",
    "If it works, don't touch it… because you'll break it.",
    "You don't fix bugs, you just make them harder to find.",
    "Your code compiles, but so do bad decisions.",
    "You're not done, you just stopped debugging.",
    "Every fix you make creates two new problems.",
    "You don't understand the bug, you just silenced it.",
    "Programming is just turning coffee into bugs.",
    "There’s always one more semicolon hiding somewhere.",
    "99% of coding is wondering why it doesn’t work.",
    "The code compiles, the problem begins.",
    "Fix one bug, discover three new features.",
    "Comments are just apologies to your future self.",
    "Nothing works the first time—and that’s tradition.",
    "Every project starts clean and ends… experienced.",
    "Debugging: where you question reality and your choices.",
    "The bug isn’t gone, it’s just waiting.",
    "Code never lies… but it doesn’t always tell the truth either.",
    "One line of code can ruin your entire day.",
    "Working code is just temporarily correct code.",
    "Refactoring means breaking it in a better way.",
    "The simplest bug takes the longest to find.",
    "If it works, no one knows why. If it breaks, everyone cares.",
    "Computers are fast at doing exactly what you told them to do wrong.",
    "Programming is guessing until it becomes logic.",
    "The problem isn’t writing code—it’s understanding it later.",
    "Every programmer has a special talent for creating new problems.",
    "Every bug you ignore becomes a future incident report.",
    "Your system doesn’t fail—it waits for the worst moment to prove a point.",
    "Dead code isn’t dead, it’s just waiting to be called.",
    "Production is where your assumptions go to die.",
    "That one ‘temporary fix’ is now a permanent liability.",
    "Logs don’t tell stories, they leave clues after the damage is done.",
    "Your code works fine… until reality interacts with it.",
    "Silence in the logs is more dangerous than errors.",
    "The bug isn’t gone, it just learned how to hide better.",
    "Your fallback plan is just another failure mode.",
    "Everything is stable… right before it isn’t.",
    "The system remembers every shortcut you took.",
    "Edge cases aren’t rare—they’re just patient.",
    "Production is just beta testing with consequences.",
    "There are only two states: it works, and it will.",
    "The code is fine… the universe just disagrees.",
    "If you didn’t log it, it didn’t happen—and it will again.",
    "Nothing is truly deleted, just waiting for a comeback.",
    "The bug isn’t in your code, it’s in your assumptions.",
    "Your system is stable until a user touches it.",
    "Every ‘impossible’ bug just hasn’t happened yet.",
    "Working software is just software that hasn’t met reality.",
    "The deeper you debug, the less you trust anything.",
    "Eventually, every shortcut becomes the main road.",
    "The problem isn’t reproducible… until it matters.",
    "Undefined behavior means the program has free will.",
    "You don’t find bugs, you uncover decisions.",
    "The system works perfectly in an environment that doesn’t exist.",
    "Your backup plan is just future evidence.",
    "Nothing breaks during testing—it saves that for later.",
    "Every fix is a trade—you just don’t know the cost yet.",
    "Code doesn’t age well, it decays quietly.",
    "That ‘one small change’ is never small.",
    "In theory, everything works. In practice, theory fails.",
    "The bug report always arrives after your confidence does.",
    "You don’t control complexity—you negotiate with it.",
    "The system isn’t broken, it’s misunderstood.",
    "Eventually, every abstraction leaks—and so does your sanity.",
    "The more layers you add, the less you see.",
    "Every system becomes legacy faster than expected.",
    "Your code doesn’t forget—it remembers everything you ignored.",
    "Your code doesn’t break loudly, it erodes quietly.",
    "Every dependency is a risk you agreed to.",
    "The issue wasn’t fixed, it just changed form.",
    "Your codebase grows… so do the unseen cracks.",
    "Success hides problems, failure exposes them.",
    "Nothing crashes until it matters most.",
    "Your clean design fades the moment scale shows up.",
    "You write code like you're racing, but debugging proves you're not winning.",
    "You don't build features, you accumulate technical debt.",
    "You spend hours debugging something a senior would fix in minutes.",
    "Your solution works, but it's not the right one.",
    "You rely on luck more than logic.",
    "Your code passes tests you didn't write properly.",
    "You don't control your codebase, it controls you.",
    "You rewrite code not to improve it, but because you forgot how it works.",
    "You debug symptoms while ignoring the real problem.",
    "Half your code is 'temporary' from 6 months ago.",
    "You trust code you don't understand way too much.",
    "You write comments for things you should've named properly.",
    "Your code only works on your machine… barely.",
    "You fear refactoring because you know it'll break everything.",
    "You spend more time fixing than building.",
    "Your commits say 'fix' because you don't know what you fixed.",
    "You don't solve problems, you patch symptoms.",
    "You rely on autocomplete more than your brain.",
    "Your code has more plot twists than your life.",
    "You open 20 tabs to fix one bug… and forget which one mattered.",
    "Your brain runs out of RAM before your system does.",
    "You rename variables like it’ll fix your logic.",
    "Your code reviews are just you judging your past self.",
    "You celebrate 'it works' like you solved world hunger.",
    "You start coding fast… then spend hours undoing it.",
    "You debug like you're playing hide and seek with your mistakes.",
    "Your TODO list is just a graveyard of intentions.",
    "You fix one thing and suddenly everything takes it personally.",
    "You stare at your code hoping it explains itself.",
    "You press run like you're rolling dice.",
    "Your confidence drops the moment someone watches you code.",
    "You say 'easy fix'… then disappear for hours.",
    "You don’t lose bugs, you just lose track of them.",
    "Your code works better when you don’t touch it.",
    "You spend more time thinking about coding than actually understanding it.",
    "You trust your code right until it betrays you.",
    "You read your own code like it was written by a stranger.",
    "You don’t write bugs… they just feel at home in your code.",
    "You've never fully understood your own project.",
    "You think it's optimized… it's not.",
    "You're one bug away from losing control.",
    "You say you're good at handling exceptions… just not in life.",
    "You love breaking things… especially in production.",
    "You're great at committing… just not relationships.",
    "You keep pushing… even when no one asked you to.",
    "You know how to handle threads… but still lose focus.",
    "You deal with memory leaks… but forget everything else.",
    "You optimize performance… but not your own time.",
    "You always return something… except effort.",
    "You handle multiple arguments… but never win them.",
    "You like to go deep… but only in nested loops.",
    "You debug code all day… but can't fix your own mistakes.",
    "You keep things running… just not your life.",
    "You chase performance… while wasting your own potential.",
    "You know how to handle crashes… just not failure.",
    "You refactor code… but never yourself.",
    "You solve problems… until they involve thinking.",
    "You rely on logic… until it's time to use it.",
    "You write efficient code… and live inefficiently.",
    "You build systems… but can't build discipline.",
    "You fix errors… but ignore the obvious ones in yourself.",
    "You don’t write code, you leave behind puzzles no one asked for.",
    "Your logic collapses the moment it meets a real use case.",
    "You don’t create systems, you accumulate side effects.",
    "Your code isn’t flexible, it’s fragile in disguise.",
    "You don’t understand flow, you just follow it blindly.",
    "Your fixes don’t solve problems, they delay them.",
    "You don’t reduce complexity, you relocate it.",
    "Your code behaves… until someone actually uses it.",
    "You don’t anticipate failure, you react to it too late.",
    "Your structure looks fine… until it has to scale.",
    "You don’t test logic, you test luck.",
    "Your code isn’t wrong, it’s accidentally right.",
    "You don’t know why it works, just when it stops.",
    "Your changes fix today and ruin tomorrow.",
    "You don’t build clarity, you bury confusion deeper.",
    "Your code passes checks, not understanding.",
    "You don’t simplify problems, you just hide them better.",
    "Your output looks correct… your reasoning isn’t.",
    "You don’t master tools, you depend on them.",
    "Your code doesn’t evolve, it decays slowly.",
    "Your code doesn’t fail loudly… it quietly embarrasses you.",
    "You don’t write bugs, you engineer long-term regret.",
    "Your logic isn’t wrong, it’s just missing.",
    "You treat undefined behavior like a feature.",
    "Your code runs… like a ticking time bomb.",
    "You don’t understand the system, you just survive inside it.",
    "Your commits tell a story… none of it makes sense.",
    "You don’t debug code, you interrogate it until it confesses.",
    "Your codebase isn’t complex, it’s confused.",
    "You optimize for now and pay for it forever.",
    "You don’t break things intentionally… but it still happens every time.",
    "Your fixes age worse than the bugs they replace.",
    "You don’t control edge cases, they control you.",
    "Your code works best when no one looks too closely.",
    "You don’t write maintainable code, you write future problems.",
}
